### ISSUE TITLE
Time on popup when you click on a scheduled check-in is different from actual time of scheduled check-in.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/tenfour-mobile#387]
#### Expected Behaviour
When you click on a scheduled check-in to see more details, the details on the popup should match the actual details of the check-in.
#### Actual Behaviour
When you click on a scheduled check-in to see more details, the time on the popup is different from the time on the actual check-in. Where there are several scheduled check-ins, when you open each one, the popup shows the same time, which is wrong.
#### Steps to Reproduce
- Create check-ins scheduled hourly. 
- Navigate to the Scheduled tab.
- Click on any one of the scheduled checkins.
 - Note that they all show a time of 11:15 AM.

#### Screenshot
![Screenshot from 2019-05-17 18-47-40.png](https://images.zenhubusercontent.com/5c08f5bfba2cce399c79d9e2/98d07666-ce53-4270-8c5b-0c60c302a8cd)

#### Environment
- [ ] www.tenfour.org
- [ ] app.tenfour.org
- [x] staging.tenfour.org
- [ ] dev.tenfour.org
- [ ] localhost:8100
- [ ] iOS App (live)
- [ ] iOS App (testflight)
- [ ] Android App (live)
- [ ] Android App (beta)

**Comment by dalezak** [comment]
@Obadha2 I believe this has already been fixed, and working correctly on https://ushahidi.staging.tenfour.org. Can you re-test to verify?

### List
![kHLwWXXw](https://user-images.githubusercontent.com/91811/59063852-3e03f800-8866-11e9-8616-7d4275603205.png)

### Details
![JztD18Bw](https://user-images.githubusercontent.com/91811/59063860-44926f80-8866-11e9-9de1-fbd28530633d.png)

**Comment by Obadha2** [comment]
Alright this looks good! :+1:
