### ISSUE TITLE
Time and Date of when check-in is sent should be included in email subject line.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/tenfour-mobile#390]
#### Expected Behaviour
Email notifications that are received for scheduled check-ins should include time and date in subject line.
#### Actual Behaviour
Currently, when an email notification for scheduled check-ins is received in the inbox, the subject is the title of the check-in itself.

#### Screenshots
Emails received:
![Screenshot from 2019-05-17 14-06-50.png](https://images.zenhubusercontent.com/5c08f5bfba2cce399c79d9e2/62437eaf-8ef4-44a4-9f96-874028360d83)

Conversation to implement:
![Screenshot from 2019-05-17 20-00-17.png](https://images.zenhubusercontent.com/5c08f5bfba2cce399c79d9e2/f6ae375c-5ba9-4828-8041-a611666b3d9f)

#### Environment
- [ ] www.tenfour.org
- [ ] app.tenfour.org
- [x] staging.tenfour.org
- [ ] dev.tenfour.org
- [ ] localhost:8100
- [ ] iOS App (live)
- [ ] iOS App (testflight)
- [ ] Android App (live)
- [ ] Android App (beta)

**Comment by rowasc** [comment]
ah. OK , google isn't really grouping them for me. They are actually duplicated/sent twice. So maybe this isn't needed if that's the case?

**Comment by mackers** [comment]
@rowasc Ahh ok they are duplicated, so this issue is invalid
