### ISSUE TITLE
Save check-in to re-use later check-box disappears on check-in creation modal.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/tenfour-mobile#395]
#### Expected Behaviour
All fields should be visible at all times.
#### Actual Behaviour
When user opens modal to create check-in, all fields are visible. However, when they select someone to receive the check-in, the last field on the form which is the Save check-in to re-use later check-box disappears!
#### Steps to Reproduce
- Open check-in creation modal.
- Note that on the details form, the Save this check-in to re-use later check-box is visible.
- Click Send to field and select a recipient.
- Note that now the Save this check-in to re-use later check-box has disappeared.
- If you click back at this point to the first modal where the name of the check-in is provided, then click Next to the next step, the Save this check-in to re-use later check-box is now visible.

#### Environment
- [ ] www.tenfour.org
- [ ] app.tenfour.org
- [ ] staging.tenfour.org
- [x] dev.tenfour.org
- [ ] localhost:8100
- [ ] iOS App (live)
- [ ] iOS App (testflight)
- [ ] Android App (live)
- [ ] Android App (beta)

**Comment by dalezak** [comment]
_Ah-ha!_ Found the problem @Obadha2, the `Save this check-in to re-use later` checkbox is still there, except it's below the footer toolbar. I'll need to trigger recalculating the content space, it should resolve the issue.

**Comment by dalezak** [comment]
@Obadha2 the fix worked, will send to @mackers for review :+1: 

![8wVXzjvg](https://user-images.githubusercontent.com/91811/59293030-91e25880-8c3b-11e9-91aa-294507681387.png)

**Comment by Obadha2** [comment]
QA'd, passes. :+1:
