### ISSUE TITLE
On creating check-in, user can select past time in the when field.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/tenfour-mobile#398]
#### Expected Behaviour
User should only be able to send check-in from the time now and not from the past.

#### Actual Behaviour
The date/time picker that pops up allows user to select a time that is in the past. They can then go ahead and send a check-in. Check-ins will be sent as scheduled for all set times i.e if a check-in was scheduled five hours ago to go out hourly, a check-in will go out for each hour past.
#### Steps to Reproduce
- Navigate to create check-in modal.
- Click on When field to open date/time picker.
- Note that while you cannot select a past date, you can select a past time.
- User can save and send out check-in.

#### Environment
- [ ] www.tenfour.org
- [ ] app.tenfour.org
- [x] staging.tenfour.org
- [ ] dev.tenfour.org
- [ ] localhost:8100
- [ ] iOS App (live)
- [ ] iOS App (testflight)
- [ ] Android App (live)
- [ ] Android App (beta)

**Comment by dalezak** [comment]
Welcome to the future!

<img width="780" alt="Screenshot 2019-06-06 14 01 13" src="https://user-images.githubusercontent.com/91811/59062684-abfaf000-8863-11e9-93df-a68d5e8798a3.png">

**Comment by Obadha2** [comment]
@dalezak  Has this fix been pushed to staging? 
Also, can it say "....specify When to be a time in the future...." because actually it's a past time and not date that can be selected.

**Comment by dalezak** [comment]
@Obadha2 I can change the toast to say `time` instead of `date` 👍 

This is still waiting for review from @mackers, so hasn't been merged yet, stay tuned!

**Comment by Obadha2** [comment]
QA'd, passes.
