### ISSUE TITLE
Some emails are sent multiple times when check-ins have Call or SMS option selected.

### ISSUE THREAD

**Issue by Obadha2** [ushahidi/tenfour-mobile#407]
#### Expected Behaviour
Single emails should be sent out for every check-in.

#### Actual Behaviour
Check-ins are having emails sent out in 10s, 2s, 4s, etc

#### Steps to Reproduce
- Create a check-in. 
- Make sure you select Email and Voice Call in Send Via options..
- Note that when the check-in is going out, 10 emails are sent out instead of one.
- Also, note that Voice Calls are not made for the check-ins.

#### Environment
- [ ] www.tenfour.org
- [x] app.tenfour.org PROD
- [x] staging.tenfour.org
- [ ] dev.tenfour.org
- [ ] localhost:8100
- [ ] iOS App (live)
- [ ] iOS App (testflight)
- [ ] Android App (live)
- [ ] Android App (beta)

**Comment by rowasc** [comment]
>Update: Issue still occurs even when check-in is not scheduled, when Send Now has been selected.
@Obadha2 can you try to repro it in production (for normal checkins)? I want to isolate and see if it's a regression or not

**Comment by Obadha2** [comment]
*Update:* This happens the same way for SMS too. 
Where call option has been selected, 7 SMSs are received. 
If not, only one SMS is received.

**Comment by rowasc** [comment]
Confirmed that this happens in production (@mackers  checked it for us today ) so it's definitely a bug, but not a regression 🤔 .

**Comment by mackers** [comment]
- email, voice, sms = x10 <-- BROKEN
- email, sms = x1

**Comment by mackers** [comment]
Fixed now.
